### ISSUE TITLE
Tried to use the most basic example and cannot produce a record

### ISSUE THREAD

**Issue by Zordid** [kotest/kotest-extensions-embedded-kafka#20]
I simply try to do the most basic example, using the embedded Kafka as shown on the documentation on Kotest.

When I try to produce my very first record, I get this exception:
```
ERROR k.s.KafkaApis - [KafkaApi-0] Unexpected error handling request RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=producer-1, correlationId=0, headerVersion=2) -- ApiVersionsRequestData(clientSoftwareName='apache-kafka-java', clientSoftwareVersion='3.5.1') with context RequestContext(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=producer-1, correlationId=0, headerVersion=2), connectionId='127.0.0.1:6001-127.0.0.1:58379-0', clientAddress=/127.0.0.1, principal=User:ANONYMOUS, listenerName=ListenerName(PLAINTEXT), securityProtocol=PLAINTEXT, clientInformation=ClientInformation(softwareName=unknown, softwareVersion=unknown), fromPrivilegedListener=true, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@73e2a232])
java.lang.NoSuchMethodError: 'org.apache.kafka.common.requests.ApiVersionsResponse org.apache.kafka.common.requests.ApiVersionsResponse.createApiVersionsResponse(int, org.apache.kafka.common.record.RecordVersion, org.apache.kafka.common.feature.Features, java.util.Map, long, org.apache.kafka.clients.NodeApiVersions, org.apache.kafka.common.message.ApiMessageType$ListenerType)'
	at kafka.server.DefaultApiVersionManager.apiVersionResponse(ApiVersionManager.scala:89) ~[kafka_2.13-3.4.0.jar:?]
	at kafka.server.KafkaApis.createResponseCallback$1(KafkaApis.scala:1830) ~[kafka_2.13-3.4.0.jar:?]
	at kafka.server.KafkaApis.$anonfun$handleApiVersionsRequest$1(KafkaApis.scala:1833) ~[kafka_2.13-3.4.0.jar:?]
	at kafka.server.KafkaApis.$anonfun$handleApiVersionsRequest$1$adapted(KafkaApis.scala:1833) [kafka_2.13-3.4.0.jar:?]
	at kafka.server.RequestHandlerHelper.sendResponseMaybeThrottle(RequestHandlerHelper.scala:128) ~[kafka_2.13-3.4.0.jar:?]
	at kafka.server.KafkaApis.handleApiVersionsRequest(KafkaApis.scala:1833) [kafka_2.13-3.4.0.jar:?]
	at kafka.server.KafkaApis.handle(KafkaApis.scala:201) [kafka_2.13-3.4.0.jar:?]
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:75) [kafka_2.13-3.4.0.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
08:38:48.767 [kafka-producer-network-thread | producer-1] WARN  o.a.k.c.NetworkClient - [Producer clientId=producer-1] Received error UNKNOWN_SERVER_ERROR from node -1 when making an ApiVersionsRequest with correlation id 0. Disconnecting.
```

The code I am using is very, very basic:
```
val producer = embeddedKafkaListener.bytesBytesProducer()
producer.send(ProducerRecord("foo", "\"Hello\"".encodeToByteArray().bytes()))
producer.close()
```

I cannot figure out what this is about - can you help?

**Comment by Kantis** [comment]
Looks like an inconsistency between dependency versions. Check which version of kafka that you're pulling in. I think the kotest extension is using 2.13
